# Generated by Django 4.0.3 on 2022-06-13 15:45

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('wilaya', models.IntegerField(choices=[(0, 'Wilaya'), (1, '1- ADRAR'), (2, '2- CHLEF'), (3, '3 - LAGHOUAT'), (4, '4 - OUM BOUAGHI'), (5, '5 - BATNA'), (6, '6 - BEJAIA'), (7, '7 - BISKRA'), (8, '8 - BECHAR'), (9, '9 - BLIDA'), (10, '10 - BOUIRA'), (11, '11 - TAMANRASSET'), (12, '12 - TEBESSA'), (13, '13 - TLEMCEN'), (14, '14 - TIARET'), (15, '15 - TIZI OUZOU'), (16, '16 - ALGER'), (17, '17 - DJELFA'), (18, '18 - JIJEL'), (19, '19 - SETIF'), (20, '20 - SAIDA'), (21, '21 - SKIKDA'), (22, '22 - SIDI BEL ABBES'), (23, '23 - ANNABA'), (24, '24 - GUELMA'), (25, '25 - CONSTANTINE'), (26, '26 - MEDEA'), (27, '27 - MOSTAGANEM'), (28, "28 - M'SILA"), (29, '29 - MASCARA'), (30, '30 - OUARGLA'), (31, '31 - ORAN'), (32, '32 - EL BAYDH'), (33, '33 - ILLIZI'), (34, '34 - BORDJ BOU ARRERIDJ'), (35, '35 - BOUMERDES'), (36, '36 - EL TAREF'), (37, '37 - TINDOUF'), (38, '38 - TISSEMSILT'), (39, '39 - EL OUED'), (40, '40 - KHENCHLA'), (41, '41 - SOUK AHRASS'), (42, '42 - TIPAZA'), (43, '43 - MILA4'), (44, '44 - AÏN DEFLA'), (45, '45 - NÂAMA'), (46, '46 - AÏN TEMOUCHENT'), (47, '47 - GHARDAÏA'), (48, '48 - RELIZANE'), (49, '49 -Timimoun'), (50, '50-Bordj Badji Mokhtar'), (51, '51-Ouled Djellal'), (52, '52-Béni Abbès'), (53, '53-In Salah'), (54, '54-In Guezzam'), (55, '55-Touggourt'), (56, '56-Djanet'), (57, "57-M'Ghair"), (58, '58-El Meniaa')], default=0)),
                ('email', models.EmailField(max_length=254)),
                ('is_org', models.BooleanField(default=False)),
                ('org_document', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('location', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(null=True)),
                ('wilaya', models.IntegerField(choices=[(0, 'Wilaya'), (1, '1- ADRAR'), (2, '2- CHLEF'), (3, '3 - LAGHOUAT'), (4, '4 - OUM BOUAGHI'), (5, '5 - BATNA'), (6, '6 - BEJAIA'), (7, '7 - BISKRA'), (8, '8 - BECHAR'), (9, '9 - BLIDA'), (10, '10 - BOUIRA'), (11, '11 - TAMANRASSET'), (12, '12 - TEBESSA'), (13, '13 - TLEMCEN'), (14, '14 - TIARET'), (15, '15 - TIZI OUZOU'), (16, '16 - ALGER'), (17, '17 - DJELFA'), (18, '18 - JIJEL'), (19, '19 - SETIF'), (20, '20 - SAIDA'), (21, '21 - SKIKDA'), (22, '22 - SIDI BEL ABBES'), (23, '23 - ANNABA'), (24, '24 - GUELMA'), (25, '25 - CONSTANTINE'), (26, '26 - MEDEA'), (27, '27 - MOSTAGANEM'), (28, "28 - M'SILA"), (29, '29 - MASCARA'), (30, '30 - OUARGLA'), (31, '31 - ORAN'), (32, '32 - EL BAYDH'), (33, '33 - ILLIZI'), (34, '34 - BORDJ BOU ARRERIDJ'), (35, '35 - BOUMERDES'), (36, '36 - EL TAREF'), (37, '37 - TINDOUF'), (38, '38 - TISSEMSILT'), (39, '39 - EL OUED'), (40, '40 - KHENCHLA'), (41, '41 - SOUK AHRASS'), (42, '42 - TIPAZA'), (43, '43 - MILA4'), (44, '44 - AÏN DEFLA'), (45, '45 - NÂAMA'), (46, '46 - AÏN TEMOUCHENT'), (47, '47 - GHARDAÏA'), (48, '48 - RELIZANE'), (49, '49 -Timimoun'), (50, '50-Bordj Badji Mokhtar'), (51, '51-Ouled Djellal'), (52, '52-Béni Abbès'), (53, '53-In Salah'), (54, '54-In Guezzam'), (55, '55-Touggourt'), (56, '56-Djanet'), (57, "57-M'Ghair"), (58, '58-El Meniaa')], default=0)),
                ('participated', models.ManyToManyField(blank=True, default=None, related_name='participated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('location', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wilaya', models.IntegerField(choices=[(0, 'Wilaya'), (1, '1- ADRAR'), (2, '2- CHLEF'), (3, '3 - LAGHOUAT'), (4, '4 - OUM BOUAGHI'), (5, '5 - BATNA'), (6, '6 - BEJAIA'), (7, '7 - BISKRA'), (8, '8 - BECHAR'), (9, '9 - BLIDA'), (10, '10 - BOUIRA'), (11, '11 - TAMANRASSET'), (12, '12 - TEBESSA'), (13, '13 - TLEMCEN'), (14, '14 - TIARET'), (15, '15 - TIZI OUZOU'), (16, '16 - ALGER'), (17, '17 - DJELFA'), (18, '18 - JIJEL'), (19, '19 - SETIF'), (20, '20 - SAIDA'), (21, '21 - SKIKDA'), (22, '22 - SIDI BEL ABBES'), (23, '23 - ANNABA'), (24, '24 - GUELMA'), (25, '25 - CONSTANTINE'), (26, '26 - MEDEA'), (27, '27 - MOSTAGANEM'), (28, "28 - M'SILA"), (29, '29 - MASCARA'), (30, '30 - OUARGLA'), (31, '31 - ORAN'), (32, '32 - EL BAYDH'), (33, '33 - ILLIZI'), (34, '34 - BORDJ BOU ARRERIDJ'), (35, '35 - BOUMERDES'), (36, '36 - EL TAREF'), (37, '37 - TINDOUF'), (38, '38 - TISSEMSILT'), (39, '39 - EL OUED'), (40, '40 - KHENCHLA'), (41, '41 - SOUK AHRASS'), (42, '42 - TIPAZA'), (43, '43 - MILA4'), (44, '44 - AÏN DEFLA'), (45, '45 - NÂAMA'), (46, '46 - AÏN TEMOUCHENT'), (47, '47 - GHARDAÏA'), (48, '48 - RELIZANE'), (49, '49 -Timimoun'), (50, '50-Bordj Badji Mokhtar'), (51, '51-Ouled Djellal'), (52, '52-Béni Abbès'), (53, '53-In Salah'), (54, '54-In Guezzam'), (55, '55-Touggourt'), (56, '56-Djanet'), (57, "57-M'Ghair"), (58, '58-El Meniaa')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='pofile_pics')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Participate', 'Participate'), ('Unparticipate', 'Unperticipate')], default='Participate', max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
